version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска базы кэшей redis.
  redis:
    container_name: redis
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
      restart_policy:
        condition: always
        delay: 5s
    env_file: redis.env
    image: redis:alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"
    volumes:
      - "./redis/data/redis.conf:/data/redis.conf"

networks:
  external:
    external: true
    name: $NETWORK
