#`version: "3.5"` указывает версию формата файла Docker Compose, который будет использоваться. В данном случае это версия 3.5. Эта версия поддерживает такие возможности, как объекты `config`, `секреты` и опции `deploy` для развертывания сервисов в рое.
version: "3.5"

#Это определение сети под названием "docker_net" с именем сети по умолчанию. Эта сеть может использоваться для соединения различных служб, определенных в файле Docker Compose, позволяя им взаимодействовать друг с другом.
networks:
  docker_net:
    name: $DEFAULT_NETWORK

services:
  #`redis:` определяет службу Docker с именем `redis`, которая использует образ Redis версии `7.0.9-alpine`. Этот сервис будет запускать сервер Redis в контейнере Docker.
  redis:
    #В секции `env_file` указывается путь к файлу окружения с именем `postgres.env`. Этот файл содержит переменные окружения, которые будут передаваться контейнеру Redis во время выполнения.
    env_file:
      - "postgres.env"
    #`image: redis:7.0.9-alpine` указывает образ Docker, который будет использоваться для службы Redis. В данном случае используется образ Redis версии `7.0.9-alpine`.
    image: redis:7.0.9-alpine
    #`restart: always` - это опция конфигурации для Docker-сервиса Redis, которая указывает, что контейнер всегда должен перезапускаться, если он останавливается по какой-либо причине, например, из-за сбоя или ручной остановки. Это гарантирует, что служба Redis всегда доступна и работает.
    restart: always
    #`volumes: - "./redis/data:/data"` определяет том Docker для службы Redis. Он отображает локальный каталог `./redis/data` на каталог `/data` внутри контейнера Redis. Это позволяет сохранять данные, даже если контейнер остановлен или удален.
    volumes:
      - "./redis/data:/data"
    #`container_name: redis` задает имя контейнера Redis равным "redis". Это позволяет легко идентифицировать контейнер и управлять им, используя указанное имя вместо случайно сгенерированного.
    container_name: redis
    #`networks: - "docker_net"` определяет сеть, к которой будет подключена служба Redis. В данном случае он подключается к сети с именем "docker_net". Это позволяет контейнеру Redis взаимодействовать с другими контейнерами в той же сети.
    networks:
      - "docker_net"
